### ISSUE TITLE
Enhance Climage Example

### ISSUE THREAD

**Issue by Symbolics** [fjames86/ftw#4]
The climage example could be genuinely useful. One enhancement that is needed is to make it work as an independent window. At the moment, starting it from `slime` blocks the REPL. This enhancement would:

- Make climage a useful tool when programming
- Demonstrate non-blocking background message pumps

This requires a fairly good knowledge of Windows programming, however once the basic framework is complete less knowledgeable community members can flesh out the formatting, and use it as the basis for other tools (debugger anyone?).

**Comment by fjames86** [comment]
Hi I tried just doing the simple thing of running it from a background thread and it seemed to work fine:
`(bt:make-thread #'climage)`
So I just added a parameter to spawn from a background thread.

**Comment by Symbolics** [comment]
Too easy!
